enum Api {
  // The address does not exist
  error = '/error',
  login = '/login',
  logout = '/logout',
  getUserInfo = '/getUserInfo',
  getPermCode = '/getPermCode',
  getMenuList = '/getMenuList',
  // device
  deviceAdd = '/api/device/',
  deviceRemove = '/api/device/',
  deviceUpdate = '/api/device/',
  deviceDetectGet = '/api/device',
  deviceDetect = '/api/device',
  deviceReboot = '/deviceReboot',
  deviceProjectGet = '/deviceProjectGet',
  deviceGroupGet = '/api/area',
  // deviceGroupGet = '/deviceGroupGet',
  deviceZoneRemove = '/api/area/',
  deviceGroupAdd = '/api/area/',
  deviceGroupInfo = '/api/area/',
  deviceGroupUpdate = '/api/area/',
  // settings
  ConfigGet = '/api/control?cmd=broadcast_control',
  deviceAudioFileGet = '/api/file/bgm1',
  deviceAudioFileRemove = '/api/file/',
  deviceTimerSettingGet = '/api/schedule',
  deviceTimerSettingDelete = '/api/schedule/',
  deviceTimerSettingUpdate = '/api/schedule/',
  deviceTimerSettingAdd = '/api/schedule/',
  // deviceTimerSettingGet = '/api/schedule',
  // deviceEventGet = '/deviceEventGet',
  deviceEventGet = '/api/command',
  deviceEventAdd = '/api/command/',
  deviceEventRemove = '/api/command/',
  deviceEventUpdate = '/api/command/',
  deviceSourceGet = '/deviceSourceGet',
  deviceGpoGet = '/deviceGpoGet',
  // deviceGpiEventSettingGet = '/deviceGpiEventSettingGet',
  deviceGpiEventSettingGet = '/api/trigger',
  deviceGpiEventSettingRemove = '/api/trigger/',
  deviceGpiEventSettingAdd = '/api/trigger/',
  deviceGpiEventSettingUpdate = '/api/trigger/',
  deviceExpandSave = '/deviceExpandSave',
  userListGet = '/userListGet',
  bgmListGet = '/api/bgm',
  bgmListAdd = '/api/bgm/',
  bgmListRemove = '/api/bgm/',
}

export default Api;
